/**
 * MaintenanceNode - AI-powered maintenance and repair management node
 * Manages yacht and marina maintenance, scheduling, and technician dispatch
 */

import { BaseNode, BaseNodeOptions } from '../../core/BaseNode.js';
import { v4 as uuidv4 } from 'uuid';

export interface MaintenanceNodeConfig extends Omit<BaseNodeOptions, 'type' | 'capabilities'> {
  serviceInfo: {
    name: string;
    coverage: string[];
    specializations: string[];
  };
}

interface MaintenanceRequest {
  id: string;
  requesterId: string;
  requesterType: 'yacht' | 'marina' | 'other';
  type: 'scheduled' | 'emergency' | 'inspection';
  category: string;
  description: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'pending' | 'assigned' | 'in-progress' | 'completed' | 'cancelled';
  requestDate: Date;
  scheduledDate?: Date;
  completionDate?: Date;
  assignedTechnician?: string;
  estimatedCost?: number;
  actualCost?: number;
}

interface MaintenanceSchedule {
  id: string;
  entityId: string;
  entityType: 'yacht' | 'marina' | 'equipment';
  maintenanceType: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual';
  lastPerformed?: Date;
  nextDue: Date;
  description: string;
}

interface Technician {
  id: string;
  name: string;
  specializations: string[];
  available: boolean;
  currentJob?: string;
}

interface SparePart {
  id: string;
  name: string;
  partNumber: string;
  quantity: number;
  minStock: number;
  supplier: string;
  price: number;
  lastOrdered?: Date;
  autoOrderEnabled?: boolean;
}

interface PredictiveAnalysis {
  id: string;
  entityId: string;
  entityType: 'yacht' | 'marina' | 'equipment';
  componentName: string;
  currentCondition: number; // 0-100%
  predictedFailureDate: Date;
  confidence: number; // 0-1
  recommendations: string[];
  basedOn: {
    operatingHours?: number;
    lastMaintenance?: Date;
    historicalPattern?: string;
    sensorData?: any;
  };
}

interface HaulOutSchedule {
  id: string;
  vesselId: string;
  vesselName: string;
  type: 'routine' | 'emergency' | 'survey' | 'repair';
  scheduledDate: Date;
  estimatedDuration: number; // days
  facility: string;
  slipNumber?: string;
  workRequired: string[];
  estimatedCost: number;
  status: 'scheduled' | 'in-progress' | 'completed' | 'cancelled';
  completionDate?: Date;
}

interface WarrantyRecord {
  id: string;
  equipmentId: string;
  equipmentName: string;
  manufacturer: string;
  warrantyStart: Date;
  warrantyEnd: Date;
  coverageType: 'full' | 'parts-only' | 'labor-only' | 'limited';
  terms: string;
  claimHistory: WarrantyClaim[];
  isActive: boolean;
}

interface WarrantyClaim {
  id: string;
  date: Date;
  issue: string;
  status: 'submitted' | 'approved' | 'denied' | 'completed';
  claimAmount?: number;
  approvedAmount?: number;
}

interface SupplierOrder {
  id: string;
  partId: string;
  partName: string;
  supplierId: string;
  supplierName: string;
  quantity: number;
  unitPrice: number;
  totalCost: number;
  orderDate: Date;
  expectedDelivery: Date;
  actualDelivery?: Date;
  status: 'pending' | 'ordered' | 'shipped' | 'delivered' | 'cancelled';
  autoGenerated: boolean;
}

export class MaintenanceNode extends BaseNode {
  private serviceInfo: MaintenanceNodeConfig['serviceInfo'];
  private requests: Map<string, MaintenanceRequest> = new Map();
  private schedules: Map<string, MaintenanceSchedule> = new Map();
  private technicians: Map<string, Technician> = new Map();
  private spareParts: Map<string, SparePart> = new Map();

  // NEW: Predictive maintenance
  private predictiveAnalyses: Map<string, PredictiveAnalysis> = new Map();
  private equipmentHistory: Map<string, any[]> = new Map(); // AI learns from history

  // NEW: Haul-out management
  private haulOutSchedules: Map<string, HaulOutSchedule> = new Map();

  // NEW: Warranty tracking
  private warranties: Map<string, WarrantyRecord> = new Map();

  // NEW: Supplier orders
  private supplierOrders: Map<string, SupplierOrder> = new Map();

  constructor(config: MaintenanceNodeConfig) {
    super({
      ...config,
      type: 'ada.maintenance',
      capabilities: {
        skills: [
          'maintenance-scheduling',
          'emergency-repair',
          'technician-dispatch',
          'spare-parts-management',
          'preventive-maintenance',
          'inspection-services',
          'equipment-diagnostics',
          'maintenance-tracking',
          'predictive-maintenance', // NEW: AI predicts failures
          'condition-monitoring', // NEW: Real-time condition tracking
          'haul-out-planning', // NEW: Vessel haul-out scheduling
          'warranty-management', // NEW: Warranty tracking
          'auto-procurement', // NEW: Automatic parts ordering
          'failure-prediction', // NEW: ML-based failure prediction
        ],
        services: [
          'repair-services',
          'scheduled-maintenance',
          'emergency-response',
          'parts-supply',
          'maintenance-reporting',
          'equipment-monitoring',
          'predictive-analytics', // NEW
          'haul-out-services', // NEW
          'warranty-claims', // NEW
          'supplier-management', // NEW
          'auto-ordering', // NEW
        ],
        integrations: [
          'ada.sea',
          'ada.marina',
          'ada.finance',
          'parts-suppliers',
          'diagnostic-systems',
          'shipyard-systems', // NEW
          'warranty-systems', // NEW
          'procurement-apis', // NEW
        ],
      },
    });

    this.serviceInfo = config.serviceInfo;
    this.initializeTechnicians();
    this.initializeSpareParts();
    this.initializeWarranties();
    this.startAutomaticMonitoring();
  }

  /**
   * Initialize the Maintenance node
   */
  async initialize(): Promise<void> {
    this.logEvent('Maintenance node initializing', { service: this.serviceInfo });
    this.setupMaintenanceHandlers();
    this.logEvent('Maintenance node initialized', { id: this.identity.id });
  }

  /**
   * Process maintenance-related tasks
   */
  async processTask(task: any): Promise<any> {
    const { type, data } = task;

    switch (type) {
      case 'create-request':
        return this.createMaintenanceRequest(data);
      case 'schedule-maintenance':
        return this.schedulePreventiveMaintenance(data);
      case 'assign-technician':
        return this.assignTechnician(data);
      case 'complete-maintenance':
        return this.completeMaintenanceRequest(data);
      case 'check-spare-parts':
        return this.checkSparePartAvailability(data);
      case 'get-maintenance-history':
        return this.getMaintenanceHistory(data);
      // NEW: Predictive maintenance
      case 'predict-failures':
        return this.predictEquipmentFailures(data);
      case 'get-condition-report':
        return this.getConditionReport(data);
      // NEW: Haul-out
      case 'schedule-haulout':
        return this.scheduleHaulOut(data);
      case 'get-haulout-schedule':
        return this.getHaulOutSchedule(data);
      // NEW: Warranty
      case 'check-warranty':
        return this.checkWarranty(data);
      case 'file-warranty-claim':
        return this.fileWarrantyClaim(data);
      // NEW: Auto ordering
      case 'enable-auto-order':
        return this.enableAutoOrdering(data);
      default:
        throw new Error(`Unknown task type: ${type}`);
    }
  }

  /**
   * Get node status
   */
  getStatus(): Record<string, any> {
    const pendingRequests = Array.from(this.requests.values())
      .filter(r => r.status === 'pending' || r.status === 'assigned').length;

    const criticalRequests = Array.from(this.requests.values())
      .filter(r => r.priority === 'critical' && r.status !== 'completed').length;

    const availableTechnicians = Array.from(this.technicians.values())
      .filter(t => t.available).length;

    const lowStockParts = Array.from(this.spareParts.values())
      .filter(p => p.quantity < p.minStock).length;

    return {
      service: this.serviceInfo,
      totalRequests: this.requests.size,
      pendingRequests,
      criticalRequests,
      availableTechnicians,
      totalTechnicians: this.technicians.size,
      lowStockParts,
      totalParts: this.spareParts.size,
    };
  }

  /**
   * Create maintenance request
   */
  createMaintenanceRequest(data: {
    requesterId: string;
    requesterType: 'yacht' | 'marina' | 'other';
    type: 'scheduled' | 'emergency' | 'inspection';
    category: string;
    description: string;
    priority?: 'low' | 'medium' | 'high' | 'critical';
  }): MaintenanceRequest {
    const request: MaintenanceRequest = {
      id: uuidv4(),
      requesterId: data.requesterId,
      requesterType: data.requesterType,
      type: data.type,
      category: data.category,
      description: data.description,
      priority: data.priority || (data.type === 'emergency' ? 'critical' : 'medium'),
      status: 'pending',
      requestDate: new Date(),
    };

    this.requests.set(request.id, request);

    // Auto-assign if emergency
    if (request.type === 'emergency') {
      this.assignTechnician({ requestId: request.id });
    }

    this.remember('data', { request }, ['maintenance', 'request'], 8);

    return request;
  }

  /**
   * Schedule preventive maintenance
   */
  schedulePreventiveMaintenance(data: {
    entityId: string;
    entityType: 'yacht' | 'marina' | 'equipment';
    maintenanceType: string;
    frequency: MaintenanceSchedule['frequency'];
    description: string;
  }): MaintenanceSchedule {
    const nextDue = this.calculateNextDueDate(data.frequency);

    const schedule: MaintenanceSchedule = {
      id: uuidv4(),
      entityId: data.entityId,
      entityType: data.entityType,
      maintenanceType: data.maintenanceType,
      frequency: data.frequency,
      nextDue,
      description: data.description,
    };

    this.schedules.set(schedule.id, schedule);

    this.remember('data', { schedule }, ['maintenance', 'scheduling'], 7);

    return schedule;
  }

  /**
   * Assign technician to maintenance request
   */
  assignTechnician(data: { requestId: string; technicianId?: string }): any {
    const request = this.requests.get(data.requestId);

    if (!request) {
      return { success: false, message: 'Request not found' };
    }

    let technician: Technician | undefined;

    if (data.technicianId) {
      technician = this.technicians.get(data.technicianId);
      if (!technician || !technician.available) {
        return { success: false, message: 'Technician not available' };
      }
    } else {
      // Auto-assign available technician
      technician = Array.from(this.technicians.values())
        .find(t => t.available && t.specializations.includes(request.category));

      if (!technician) {
        return { success: false, message: 'No available technician' };
      }
    }

    request.assignedTechnician = technician.id;
    request.status = 'assigned';
    technician.available = false;
    technician.currentJob = request.id;

    this.remember('event', { request, technician }, ['assignment'], 7);

    return { success: true, request, technician };
  }

  /**
   * Complete maintenance request
   */
  completeMaintenanceRequest(data: {
    requestId: string;
    actualCost: number;
    notes?: string;
  }): any {
    const request = this.requests.get(data.requestId);

    if (!request) {
      return { success: false, message: 'Request not found' };
    }

    request.status = 'completed';
    request.completionDate = new Date();
    request.actualCost = data.actualCost;

    // Free up technician
    if (request.assignedTechnician) {
      const technician = this.technicians.get(request.assignedTechnician);
      if (technician) {
        technician.available = true;
        technician.currentJob = undefined;
      }
    }

    this.remember('data', { request, completion: data }, ['maintenance', 'completed'], 9);

    // Create invoice via Finance node
    this.createInvoiceForMaintenance(request, data.actualCost)
      .catch(error => {
        console.error('Failed to create invoice for maintenance:', error.message);
      });

    return { success: true, request };
  }

  /**
   * Create invoice for maintenance service via Finance node
   */
  private async createInvoiceForMaintenance(
    request: MaintenanceRequest,
    actualCost: number
  ): Promise<void> {
    const financeNodes = BaseNode.findNodesByType('ada.finance');
    if (financeNodes.length === 0) {
      console.log('No finance node available for invoice creation');
      return;
    }

    try {
      const invoiceResponse = await this.requestFromNode(
        financeNodes[0].getIdentity().id,
        'create-invoice',
        {
          customerId: request.requesterId,
          customerName: request.requesterId, // Would be better to store customer name
          items: [
            {
              description: `Maintenance Service - ${request.category}: ${request.description}`,
              quantity: 1,
              unitPrice: actualCost,
              vatRate: 20, // %20 KDV
            },
          ],
          withholdingRate: 0, // No withholding for maintenance services
        }
      );

      this.remember('data', {
        requestId: request.id,
        invoice: invoiceResponse,
      }, ['invoice', 'finance', 'maintenance'], 8);

      console.log(`✅ Invoice created for maintenance request ${request.id}: ${invoiceResponse.invoice?.invoiceNumber}`);
    } catch (error: any) {
      console.error(`Failed to create invoice for maintenance ${request.id}:`, error.message);
    }
  }

  /**
   * Check spare part availability
   */
  checkSparePartAvailability(data: { partNumber: string }): any {
    const part = Array.from(this.spareParts.values())
      .find(p => p.partNumber === data.partNumber);

    if (!part) {
      return { available: false, message: 'Part not found' };
    }

    return {
      available: part.quantity > 0,
      part: {
        name: part.name,
        partNumber: part.partNumber,
        quantityAvailable: part.quantity,
        price: part.price,
        needsReorder: part.quantity < part.minStock,
      },
    };
  }

  /**
   * Get maintenance history
   */
  getMaintenanceHistory(data: { entityId: string }): MaintenanceRequest[] {
    return Array.from(this.requests.values())
      .filter(r => r.requesterId === data.entityId)
      .sort((a, b) => b.requestDate.getTime() - a.requestDate.getTime());
  }

  /**
   * AI-powered predictive failure analysis
   */
  predictEquipmentFailures(data: {
    entityId: string;
    entityType: 'yacht' | 'marina' | 'equipment';
    components?: string[];
  }): PredictiveAnalysis[] {
    const predictions: PredictiveAnalysis[] = [];

    // Get maintenance history for this entity
    const history = this.getMaintenanceHistory({ entityId: data.entityId });

    // Common components to analyze
    const componentsToCheck = data.components || [
      'Engine',
      'Generator',
      'Water Maker',
      'Air Conditioning',
      'Navigation Equipment',
      'Hull Integrity',
    ];

    componentsToCheck.forEach(component => {
      // AI analyzes historical patterns
      const lastMaintenance = history.find(h =>
        h.category.toLowerCase().includes(component.toLowerCase())
      );

      // Calculate condition based on time since last maintenance
      const daysSinceLastMaintenance = lastMaintenance
        ? Math.floor(
            (new Date().getTime() - lastMaintenance.requestDate.getTime()) /
              (1000 * 60 * 60 * 24)
          )
        : 365; // Assume 1 year if no history

      // AI prediction model (simplified)
      const condition = Math.max(0, 100 - daysSinceLastMaintenance / 3.65); // Degrade 1% per 3.65 days

      // Predict failure date
      const daysUntilFailure = Math.max(0, condition * 3.65);
      const predictedFailureDate = new Date();
      predictedFailureDate.setDate(predictedFailureDate.getDate() + daysUntilFailure);

      // AI confidence (higher if we have more history)
      const confidence = Math.min(0.95, 0.5 + history.length * 0.05);

      const analysis: PredictiveAnalysis = {
        id: uuidv4(),
        entityId: data.entityId,
        entityType: data.entityType,
        componentName: component,
        currentCondition: Math.round(condition),
        predictedFailureDate,
        confidence,
        recommendations: this.generateRecommendations(condition, component),
        basedOn: {
          lastMaintenance: lastMaintenance?.requestDate,
          historicalPattern: `${history.length} previous maintenance records`,
        },
      };

      this.predictiveAnalyses.set(analysis.id, analysis);
      predictions.push(analysis);
    });

    this.remember('data', { predictions, analyzed: componentsToCheck.length }, ['predictive', 'ai'], 9);

    return predictions;
  }

  /**
   * Get condition report
   */
  getConditionReport(data: { entityId: string }): any {
    const predictions = Array.from(this.predictiveAnalyses.values()).filter(
      p => p.entityId === data.entityId
    );

    const criticalComponents = predictions.filter(p => p.currentCondition < 30);
    const warningComponents = predictions.filter(
      p => p.currentCondition >= 30 && p.currentCondition < 60
    );
    const healthyComponents = predictions.filter(p => p.currentCondition >= 60);

    const overallCondition =
      predictions.reduce((sum, p) => sum + p.currentCondition, 0) / predictions.length || 0;

    return {
      entityId: data.entityId,
      overallCondition: Math.round(overallCondition),
      componentsAnalyzed: predictions.length,
      critical: criticalComponents.length,
      warning: warningComponents.length,
      healthy: healthyComponents.length,
      predictions,
      urgentActions: criticalComponents.map(c => ({
        component: c.componentName,
        action: `Immediate maintenance required for ${c.componentName}`,
        daysUntilFailure: Math.ceil(
          (c.predictedFailureDate.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24)
        ),
      })),
    };
  }

  /**
   * Schedule haul-out
   */
  scheduleHaulOut(data: {
    vesselId: string;
    vesselName: string;
    type: HaulOutSchedule['type'];
    scheduledDate: Date;
    estimatedDuration: number;
    facility: string;
    workRequired: string[];
  }): HaulOutSchedule {
    // Calculate estimated cost based on duration and work required
    const baseCostPerDay = 500; // $500 per day for slip rental
    const workCosts = {
      'bottom-paint': 2000,
      'hull-inspection': 500,
      'propeller-service': 1000,
      'shaft-alignment': 1500,
      'through-hull-service': 800,
      'zincs-replacement': 300,
    };

    let estimatedCost = baseCostPerDay * data.estimatedDuration;
    data.workRequired.forEach(work => {
      const key = work.toLowerCase().replace(/ /g, '-');
      estimatedCost += workCosts[key as keyof typeof workCosts] || 500;
    });

    const schedule: HaulOutSchedule = {
      id: uuidv4(),
      vesselId: data.vesselId,
      vesselName: data.vesselName,
      type: data.type,
      scheduledDate: data.scheduledDate,
      estimatedDuration: data.estimatedDuration,
      facility: data.facility,
      workRequired: data.workRequired,
      estimatedCost,
      status: 'scheduled',
    };

    this.haulOutSchedules.set(schedule.id, schedule);

    this.remember('data', { schedule }, ['haul-out', 'scheduling'], 8);

    return schedule;
  }

  /**
   * Get haul-out schedule
   */
  getHaulOutSchedule(data: { vesselId?: string }): HaulOutSchedule[] {
    let schedules = Array.from(this.haulOutSchedules.values());

    if (data.vesselId) {
      schedules = schedules.filter(s => s.vesselId === data.vesselId);
    }

    return schedules.sort((a, b) => a.scheduledDate.getTime() - b.scheduledDate.getTime());
  }

  /**
   * Check warranty coverage
   */
  checkWarranty(data: { equipmentId: string }): any {
    const warranty = this.warranties.get(data.equipmentId);

    if (!warranty) {
      return {
        covered: false,
        message: 'No warranty record found for this equipment',
      };
    }

    const now = new Date();
    const isActive = now >= warranty.warrantyStart && now <= warranty.warrantyEnd;

    const daysRemaining = isActive
      ? Math.ceil((warranty.warrantyEnd.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))
      : 0;

    return {
      covered: isActive,
      warranty,
      daysRemaining,
      claimHistory: warranty.claimHistory,
      totalClaims: warranty.claimHistory.length,
      approvedClaims: warranty.claimHistory.filter(c => c.status === 'approved').length,
    };
  }

  /**
   * File warranty claim
   */
  fileWarrantyClaim(data: {
    equipmentId: string;
    issue: string;
    estimatedAmount?: number;
  }): any {
    const warranty = this.warranties.get(data.equipmentId);

    if (!warranty) {
      return { success: false, message: 'No warranty found' };
    }

    if (!warranty.isActive || new Date() > warranty.warrantyEnd) {
      return { success: false, message: 'Warranty has expired' };
    }

    const claim: WarrantyClaim = {
      id: uuidv4(),
      date: new Date(),
      issue: data.issue,
      status: 'submitted',
      claimAmount: data.estimatedAmount,
    };

    warranty.claimHistory.push(claim);

    this.remember('data', { claim, equipmentId: data.equipmentId }, ['warranty', 'claim'], 8);

    return {
      success: true,
      claim,
      warranty: warranty,
      message: 'Warranty claim submitted successfully',
    };
  }

  /**
   * Enable auto-ordering for a part
   */
  enableAutoOrdering(data: { partNumber: string; enabled: boolean }): any {
    const part = Array.from(this.spareParts.values()).find(
      p => p.partNumber === data.partNumber
    );

    if (!part) {
      return { success: false, message: 'Part not found' };
    }

    part.autoOrderEnabled = data.enabled;

    this.remember('data', { partNumber: data.partNumber, autoOrder: data.enabled }, ['auto-order'], 7);

    return {
      success: true,
      part: part,
      message: data.enabled
        ? `Auto-ordering enabled for ${part.name}. Will auto-order when stock falls below ${part.minStock}`
        : `Auto-ordering disabled for ${part.name}`,
    };
  }

  /**
   * Generate AI recommendations based on condition
   */
  private generateRecommendations(condition: number, component: string): string[] {
    if (condition < 30) {
      return [
        `URGENT: Schedule immediate maintenance for ${component}`,
        'Order replacement parts now',
        'Consider temporary replacement if available',
        'Monitor closely until serviced',
      ];
    } else if (condition < 60) {
      return [
        `Schedule maintenance for ${component} within 30 days`,
        'Prepare necessary parts and tools',
        'Review maintenance procedures',
      ];
    } else {
      return [
        `${component} in good condition`,
        'Continue routine monitoring',
        'Next service as per schedule',
      ];
    }
  }

  /**
   * Initialize warranties database
   */
  private initializeWarranties(): void {
    const warranties: WarrantyRecord[] = [
      {
        id: uuidv4(),
        equipmentId: 'ENGINE-001',
        equipmentName: 'Main Engine - Caterpillar C18',
        manufacturer: 'Caterpillar',
        warrantyStart: new Date(2023, 0, 1),
        warrantyEnd: new Date(2026, 0, 1), // 3 years
        coverageType: 'full',
        terms: 'Full parts and labor coverage for manufacturing defects',
        claimHistory: [],
        isActive: true,
      },
      {
        id: uuidv4(),
        equipmentId: 'GEN-001',
        equipmentName: 'Generator - Onan 20kW',
        manufacturer: 'Onan',
        warrantyStart: new Date(2024, 0, 1),
        warrantyEnd: new Date(2027, 0, 1), // 3 years
        coverageType: 'parts-only',
        terms: 'Parts coverage only, labor not included',
        claimHistory: [],
        isActive: true,
      },
    ];

    warranties.forEach(w => this.warranties.set(w.equipmentId, w));
  }

  /**
   * Start automatic monitoring for parts and predictive maintenance
   */
  private startAutomaticMonitoring(): void {
    // Check for low stock parts and auto-order
    setInterval(() => {
      this.checkAndAutoOrder();
    }, 60000); // Check every minute (in production, would be longer)

    this.logEvent('Automatic monitoring started', {
      autoOrderEnabled: true,
      predictiveMaintenanceEnabled: true,
    });
  }

  /**
   * Check inventory and automatically order low-stock parts
   */
  private async checkAndAutoOrder(): Promise<void> {
    const lowStockParts = Array.from(this.spareParts.values()).filter(
      p => p.quantity < p.minStock && p.autoOrderEnabled
    );

    for (const part of lowStockParts) {
      // Check if we already have a pending order
      const existingOrder = Array.from(this.supplierOrders.values()).find(
        o =>
          o.partId === part.id &&
          (o.status === 'pending' || o.status === 'ordered' || o.status === 'shipped')
      );

      if (existingOrder) {
        continue; // Already ordered
      }

      // Auto-generate order
      const orderQuantity = part.minStock * 2; // Order double the minimum
      const expectedDelivery = new Date();
      expectedDelivery.setDate(expectedDelivery.getDate() + 7); // 7 days delivery

      const order: SupplierOrder = {
        id: uuidv4(),
        partId: part.id,
        partName: part.name,
        supplierId: 'AUTO-' + part.supplier,
        supplierName: part.supplier,
        quantity: orderQuantity,
        unitPrice: part.price,
        totalCost: orderQuantity * part.price,
        orderDate: new Date(),
        expectedDelivery,
        status: 'pending',
        autoGenerated: true,
      };

      this.supplierOrders.set(order.id, order);

      this.logEvent('Auto-order generated', {
        part: part.name,
        quantity: orderQuantity,
        supplier: part.supplier,
      });

      this.remember('data', { order, autoGenerated: true }, ['auto-order', 'supplier'], 7);
    }
  }

  /**
   * Calculate next due date based on frequency
   */
  private calculateNextDueDate(frequency: MaintenanceSchedule['frequency']): Date {
    const now = new Date();
    const nextDue = new Date(now);

    switch (frequency) {
      case 'daily':
        nextDue.setDate(now.getDate() + 1);
        break;
      case 'weekly':
        nextDue.setDate(now.getDate() + 7);
        break;
      case 'monthly':
        nextDue.setMonth(now.getMonth() + 1);
        break;
      case 'quarterly':
        nextDue.setMonth(now.getMonth() + 3);
        break;
      case 'annual':
        nextDue.setFullYear(now.getFullYear() + 1);
        break;
    }

    return nextDue;
  }

  /**
   * Initialize sample technicians
   */
  private initializeTechnicians(): void {
    const techs: Technician[] = [
      {
        id: uuidv4(),
        name: 'Mehmet Yılmaz',
        specializations: ['engine', 'electrical', 'mechanical'],
        available: true,
      },
      {
        id: uuidv4(),
        name: 'Ayşe Demir',
        specializations: ['hull', 'painting', 'carpentry'],
        available: true,
      },
      {
        id: uuidv4(),
        name: 'Can Özkan',
        specializations: ['electronics', 'navigation', 'communication'],
        available: true,
      },
    ];

    techs.forEach(tech => this.technicians.set(tech.id, tech));
  }

  /**
   * Initialize sample spare parts
   */
  private initializeSpareParts(): void {
    const parts: SparePart[] = [
      {
        id: uuidv4(),
        name: 'Oil Filter',
        partNumber: 'OF-2024',
        quantity: 15,
        minStock: 5,
        supplier: 'Marine Parts Co.',
        price: 35,
      },
      {
        id: uuidv4(),
        name: 'Impeller Kit',
        partNumber: 'IMP-500',
        quantity: 8,
        minStock: 3,
        supplier: 'Marine Parts Co.',
        price: 120,
      },
      {
        id: uuidv4(),
        name: 'Anchor Chain Link',
        partNumber: 'ACL-10MM',
        quantity: 50,
        minStock: 20,
        supplier: 'Anchor Supplies Ltd.',
        price: 12,
      },
    ];

    parts.forEach(part => this.spareParts.set(part.id, part));
  }

  /**
   * Setup maintenance-specific message handlers
   */
  private setupMaintenanceHandlers(): void {
    // Maintenance request from yacht/marina
    this.communication.onMessage('request-maintenance', async (message) => {
      this.remember('conversation', message, ['maintenance-request'], 8);
      const request = this.createMaintenanceRequest(message.payload);
      return { success: true, request };
    });

    // Emergency repair request
    this.communication.onMessage('emergency-repair', async (message) => {
      this.remember('conversation', message, ['emergency'], 9);
      const request = this.createMaintenanceRequest({
        ...message.payload,
        type: 'emergency',
        priority: 'critical',
      });
      return { success: true, request, eta: '30 minutes' };
    });

    // Spare parts inquiry
    this.communication.onMessage('parts-inquiry', async (message) => {
      const result = this.checkSparePartAvailability(message.payload);
      return result;
    });

    // Service status
    this.communication.onMessage('service-inquiry', async (message) => {
      return {
        service: this.serviceInfo,
        status: this.getStatus(),
      };
    });
  }
}
